Dev
jeron1moo/todo pull request #1
Opened 2021-08-04 15:20 UTC by jeron1moo

2021-08-05 13:22 UTC, jeron1moo commented on src/components/Modal/Modal.jsx
> +
это можно заменить коллбэком, но я ещё не знаю того, как красиво все это сделать.. тип, передавать функцию закрытия в этот компонент выше..(в навбаре, наверное, но снова же, получается странно)

2021-08-05 20:34 UTC, igorTT commented on src/components/Modal/Modal.jsx
> +
Попробуй https://reactjs.org/docs/react-api.html#cloneelement

2021-08-05 20:49 UTC, igorTT requested changes
Намного лучше. store для редакса хорошо написан, немножко нэйминг поменяем.
В целом всё хорошо, мелкие правки скорее улучшения)

2021-08-05 20:49 UTC, igorTT commented on src/components/Todo/Todo.jsx
> +      </Box>
Попоробуй избавится от этих обёрток на верхнем уровне
Классы прокинь как prop 'className', в компоненте объяви rootClass = \`${classes.root} ${props.className || ''}\`

2021-08-05 20:49 UTC, igorTT commented on src/components/TodoItem/TodoItem.jsx
> +              </IconButton>
Вынеси в отдельный компонент, прими туда state и onClick

2021-08-05 20:49 UTC, igorTT commented on src/components/Modal/styles.js
> +  },
Спозиционируй её абсолютно в правом верхнем углу

2021-08-05 20:49 UTC, igorTT commented on src/components/TodoList/TodoList.jsx
> +}))(TodoList);
useSelector

2021-08-05 20:49 UTC, igorTT commented on src/components/TodoNav/TodoNav.jsx
> +}))(TodoNav);
useSelector

2021-08-06 17:40 UTC, igorTT approved these changes

2021-08-06 17:41 UTC, merged