tag TODO, INPROGRESS, DONE
jeron1moo/todo pull request #11
Opened 2021-08-06 12:21 UTC by jeron1moo

2021-08-06 12:22 UTC, jeron1moo commented
единственное.. я не понимаю соовсем как поменять цвет селекта при hover и active

2021-08-07 08:00 UTC, igorTT commented on src/components/TodoTag/styles.js
> +    '& *': {
Постарайся избегать * обращений в css
css парсится справа на лево
https://stackoverflow.com/questions/5797014/why-do-browsers-match-css-selectors-from-right-to-left

2021-08-09 17:58 UTC, igorTT requested changes
В целом всё хорошо. Мелкие правки. После того, как поправишь- смерджи сам.

2021-08-09 17:58 UTC, igorTT commented on src/components/TodoItem/TodoItem.jsx
> +        </Box>
Занеси эту обёртку в TodoTag, если надо. Имя класса прими через props

2021-08-09 17:58 UTC, igorTT commented on src/components/TodoList/TodoList.jsx
>    };
Передай лучше пропсами по отдельности, так будет читабельнее

2021-08-09 17:58 UTC, igorTT commented on src/components/TodoTag/TodoTag.jsx
> +        <MenuItem value="IN_PROGRESS">In porgress</MenuItem>
Значения вынеси в константы

2021-08-10 07:06 UTC, merged