Filter field #39
jeron1moo/todo pull request #42
Opened 2021-08-13 16:09 UTC by jeron1moo

2021-08-16 19:20 UTC, igorTT requested changes
Не работает по нажатию enter

2021-08-16 19:20 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +    const searchParam = matchSorter(titles, e.target.textContent);
Зачем тут лезть аж в textContent, если значение приходит в values?

2021-08-16 19:20 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +  const [tags, setTags] = useState([]);
Что это? Зачем тут массив?

2021-08-16 19:20 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +  }, [tags]);
Нельзя вот это вызывать сразу в хэндлере?

2021-08-16 19:20 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +  const onTagsChange = (e, values) => {
tags?

2021-08-16 19:20 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +    return setTitles(Array.from(new Set(data.map((t) => t.title))));
Тут идёт присвоение при размонтирование. Это так задумано?)

2021-08-17 08:04 UTC, jeron1moo commented on src/components/FilterField/FilterField.jsx
> +  }, [tags]);
вроде нет

2021-08-17 08:05 UTC, jeron1moo commented on src/components/FilterField/FilterField.jsx
> +  const [tags, setTags] = useState([]);
масив названий по чему сортировать и массив, который я сейчас переименовал в filters, содержащий значения, которые содержатся в autocomplete, которые надо соритровать

2021-08-17 19:33 UTC, igorTT requested changes
У меня ещё куча вопросов по этой фильтрации- завтра разберём.

2021-08-17 19:33 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +  const [filters, setFilters] = useState([]);
Я не могу понять, что это за фильтра? Может быть это значения?

2021-08-17 19:33 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +    return setFilters([...matchSorter(titles, values), values]);
Зачем тут передаётся значение values? Оно же будет содержаться в результате вызова.
Тут не надо создававть новый массив.

2021-08-17 19:33 UTC, igorTT commented on src/components/FilterField/FilterField.jsx
> +  const onTagsChange = (e, values) => {
В values вроде одно значение приходит. Замени на value.

2021-08-18 18:57 UTC, igorTT requested changes
Разберись со строкой, по поводу которой комментарий и смерджи

2021-08-18 18:57 UTC, igorTT commented on src/hooks/useFilters.js
> +    stateFilter().map((t) => title.includes(t.title));
Вот эта строка похоже ничего не делает

2021-08-19 06:31 UTC, merged